select * from customer_shopping_behaviour limit 5;

-- Q1 what is the total revenue generated by male vs female customers?-- 
select gender , sum(purchase_amount) as total_spending 
from customer_shopping_behaviour 
group by gender;
 
-- Q2 segment customers into new, returning , and loyal based on their total 
--  number of previous purchases, andd show the count of each segment
with customers as (select customer_id,previous_purchases,
CASE 
when previous_purchases = 1 THEN "NEW"
when previous_purchases between 2 and 10 THEN "Returning"
else "LOYAL"
end  as customer_segment
from customer_shopping_behaviour)
select customer_segment,count(*) as "Numbers of customers"
from customers
group by customer_segment;

-- Q3 which types of gender is occur most vs spendig-- 
select gender , count(*) as total_orders,
sum(purchase_amount) as total_spending
from customer_shopping_behaviour
group by gender;

-- Q4 which product category customer spend most -- 
select category,sum(purchase_amount) as total_spend
from customer_shopping_behaviour
group by category;

-- Q5 Top 10 product -- 
select item_purchased , sum(purchase_amount) as total_spending
from customer_shopping_behaviour
group by item_purchased
order by sum(purchase_amount) desc limit 10;
-- Q6 what are the top 3 most purchaase product within each category
with item_count as (select category,item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() OVER(partition by category order by count(customer_id) desc) as item_rank
from customer_shopping_behaviour
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_count
where item_rank <= 3;


-- Q7 which customers used a discount but still spent more than the average purchase amount?--  
select customer_id,purchase_amount
from customer_shopping_behaviour
where discount_applied="Yes" and purchase_amount > (select avg(purchase_amount) as average_amount 
from customer_shopping_behaviour)

-- Q8 which are the top 5 products with highest average reveiw rating?-- 
select item_purchased,round(avg(review_rating),2) as avg_review from 
customer_shopping_behaviour group by item_purchased
order by round(avg(review_rating),2) desc limit 5;

-- Q9 compare  the average purchase amount between standard an express shipping--  
select shipping_type,
round(avg(purchase_amount),2) as avg_purchase_amount
from customer_shopping_behaviour
where shipping_type in ("Standard","Express")
group by shipping_type

-- Q10 Do subsccirbed customer spend more ? compare average spend and total revenue 
-- between subsribers an non-subscirbers
select subscription_status, 
    count(customer_id) as total_customers ,
    round(avg(purchase_amount),2) as avg_spend,
    round(sum(purchase_amount),2) as total_revenue
from customer_shopping_behaviour
group by subscription_status
order by total_customers,total_revenue,avg_spend desc;

-- Q11 which 5 products have the highest percentage of purchase with discount applied?-- 
select item_purchased,
round(100.0*sum(case when discount_applied = "Yes" THEN 1 ELSE 0 END)/count(*),2) as discount_rate
from customer_shopping_behaviour
group by item_purchased 
order by discount_rate desc 
limit 5 ;

-- Q12 Are customer who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer_shopping_behaviour
where previous_purchases > 5
group by subscription_status;

-- Q13 what is the revenue contribution of each group ?--
select 
age_group ,
sum(purchase_amount) as total_revenue
from customer_shopping_behaviour
group by age_group
order by total_revenue desc; 

-- Q14 In which season which gender gives orders most ? -- 
select season,gender,category,count(customer_id) as total_orders
from customer_shopping_behaviour
group by season,gender,category
order by count(customer_id) desc limit 10;
